### ISSUE TITLE
TypeError: Invalid URL

### ISSUE THREAD

**Issue by xxbbxx825** [danielroe/nuxt-vitest#135]
Hello, Thanks for the nice library.
I got the following issue.
If you know of a solution, we would like to know.

- libralies 
  - "nuxt": "^3.3.3"
  - "happy-dom": "^8.9.0"
  - "nuxt-vitest": "^0.6.10"
  - "vitest": "^0.29.2"
  -  "@testing-library/vue": "^6.6.1"

```
// Error messages
TypeError: Invalid URL
    at new NodeError (node:internal/errors:371:5)
    at onParseError (node:internal/url:552:9)
    at new URL (node:internal/url:628:5)
    at Function.fetchSync (/Users/me/Project/nuxt-app/node_modules/vitest-environment-nuxt/node_modules/happy-dom/src/fetch/ResourceFetch.ts:35:23)
    at Function.loadExternalScript (/Users/me/Project/nuxt-app/node_modules/vitest-environment-nuxt/node_modules/happy-dom/src/nodes/html-script-element/ScriptUtility.ts:62:26)
    at HTMLScriptElement._connectToNode (/Users/me/Project/nuxt-app/node_modules/vitest-environment-nuxt/node_modules/happy-dom/src/nodes/html-script-element/HTMLScriptElement.ts:195:19)
    at Function.appendChild (/Users/me/Project/nuxt-app/node_modules/vitest-environment-nuxt/node_modules/happy-dom/src/nodes/node/NodeUtility.ts:70:16)
    at Function.appendChild (/Users/me/Project/nuxt-app/node_modules/vitest-environment-nuxt/node_modules/happy-dom/src/nodes/element/ElementUtility.ts:70:16)
    at HTMLElement.appendChild (/Users/me/Project/nuxt-app/node_modules/vitest-environment-nuxt/node_modules/happy-dom/src/nodes/element/Element.ts:374:25)
    at Function.appendChild (/Users/me/Project/nuxt-app/node_modules/vitest-environment-nuxt/node_modules/happy-dom/src/nodes/node/NodeUtility.ts:51:18) {
  input: 'public/jquery.min.js',
  code: 'ERR_INVALID_URL'
}
TypeError: Invalid URL
    at new NodeError (node:internal/errors:371:5)
    at onParseError (node:internal/url:552:9)
    at new URL (node:internal/url:628:5)
    at Function.fetchSync (/Users/me/Project/nuxt-app/node_modules/vitest-environment-nuxt/node_modules/happy-dom/src/fetch/ResourceFetch.ts:35:23)
    at Function.loadExternalScript (/Users/me/Project/nuxt-app/node_modules/vitest-environment-nuxt/node_modules/happy-dom/src/nodes/html-script-element/ScriptUtility.ts:62:26)
    at HTMLScriptElement._connectToNode (/Users/me/Project/nuxt-app/node_modules/vitest-environment-nuxt/node_modules/happy-dom/src/nodes/html-script-element/HTMLScriptElement.ts:195:19)
    at Function.appendChild (/Users/me/Project/nuxt-app/node_modules/vitest-environment-nuxt/node_modules/happy-dom/src/nodes/node/NodeUtility.ts:70:16)
    at Function.appendChild (/Users/me/Project/nuxt-app/node_modules/vitest-environment-nuxt/node_modules/happy-dom/src/nodes/element/ElementUtility.ts:70:16)
    at HTMLElement.appendChild (/Users/me/Project/nuxt-app/node_modules/vitest-environment-nuxt/node_modules/happy-dom/src/nodes/element/Element.ts:374:25)
    at Function.appendChild (/Users/me/Project/nuxt-app/node_modules/vitest-environment-nuxt/node_modules/happy-dom/src/nodes/node/NodeUtility.ts:51:18) {
  input: 'public/js/popper.min.js',
  code: 'ERR_INVALID_URL'
}
TypeError: Invalid URL
    at new NodeError (node:internal/errors:371:5)
    at onParseError (node:internal/url:552:9)
    at new URL (node:internal/url:628:5)
    at Function.fetchSync (/Users/me/Project/nuxt-app/node_modules/vitest-environment-nuxt/node_modules/happy-dom/src/fetch/ResourceFetch.ts:35:23)
    at Function.loadExternalScript (/Users/me/Project/nuxt-app/node_modules/vitest-environment-nuxt/node_modules/happy-dom/src/nodes/html-script-element/ScriptUtility.ts:62:26)
    at HTMLScriptElement._connectToNode (/Users/me/Project/nuxt-app/node_modules/vitest-environment-nuxt/node_modules/happy-dom/src/nodes/html-script-element/HTMLScriptElement.ts:195:19)
    at Function.appendChild (/Users/me/Project/nuxt-app/node_modules/vitest-environment-nuxt/node_modules/happy-dom/src/nodes/node/NodeUtility.ts:70:16)
    at Function.appendChild (/Users/me/Project/nuxt-app/node_modules/vitest-environment-nuxt/node_modules/happy-dom/src/nodes/element/ElementUtility.ts:70:16)
    at HTMLElement.appendChild (/Users/me/Project/nuxt-app/node_modules/vitest-environment-nuxt/node_modules/happy-dom/src/nodes/element/Element.ts:374:25)
    at Function.appendChild (/Users/me/Project/nuxt-app/node_modules/vitest-environment-nuxt/node_modules/happy-dom/src/nodes/node/NodeUtility.ts:51:18) {
  input: 'public/js/bootstrap.min.js',
  code: 'ERR_INVALID_URL'
}
DOMException: Failed to perform request to "/css/bootstrap.min.css". Status code: 404
    at Function.fetch (/Users/me/Project/nuxt-app/node_modules/vitest-environment-nuxt/node_modules/happy-dom/src/fetch/ResourceFetch.ts:19:10)
DOMException: Failed to perform request to "/font/bootstrap-icons.css". Status code: 404
    at Function.fetch (/Users/me/Project/nuxt-app/node_modules/vitest-environment-nuxt/node_modules/happy-dom/src/fetch/ResourceFetch.ts:19:10)
```

```TypeScript
//nuxt.config.ts

export default defineNuxtConfig({
// ...
  app: {
    head: {
      script: [
        { src: 'public/jquery.min.js', body: true },
        { src: 'public/js/popper.min.js', body: true },
        { src: 'public/js/bootstrap.min.js', body: true },
      ],
      link: [
        { rel: 'stylesheet', href: '/css/bootstrap.min.css' },
        { rel: 'stylesheet', href: '/font/bootstrap-icons.css' },
      ],
    },
  },
})
```

```TypeScript
// vitest.config.ts
import { defineVitestConfig } from 'nuxt-vitest/config'

export default defineVitestConfig({
  test: {
    globals: true,
    globalSetup: 'tests/setup.ts',
    environment: 'happy-dom',
    coverage: {
      provider: 'c8',
      include: ['components/**/*.{vue}', 'composables/**/*.{js,ts}', 'utils/**/*.{js,ts}'],
      exclude: [],
      all: true,
    },
  },
  resolve: {
    alias: {},
  },
})
```

```TypeScript
// component.nuxt.test.ts
import { render } from '@testing-library/vue'
import Component from '~/components/organisms/submitForm/SubmitForm.vue'
const TestComponent = defineComponent({
  components: { Component },
  props: Component.props,
  template: '<Suspense><Component/></Suspense>',
})

const wrapper = render(TestComponent, {
  global: {},
})
describe(`[${TestComponent.__name}]`, () => {
  test('正常系', () => {
    expect(true).toBe(true)
  })
})
```

**Comment by proalaa** [comment]
+1

**Comment by danielroe** [comment]
Would you provide a reproduction, please? 🙏  You can use this playground to start with: ▶️  Playground
